### ISSUE TITLE
How can I watch the report in Gmail?

### ISSUE THREAD

**Issue by YuvalAdler** [davehunt/pytest-html#25]
Hi,
I managed to send the html result (say report.html) through mail, but Gmail shows the mail without all the coloring, tables etc.
Any idea?
Here's out it looks on Chrome (great) and Gmail (not so great). I guess I miss something in my e-mail header:
To: yuval.adler@kukuriku.net
From: Integration@kukuriku.net
Content-Type: text/html; charset=UTF-8
Subject: kuka

<!DOCTYPE html><html>
  <head>
    <meta charset="utf-8"/>
...

Thanks!
Yuval.

Chrome:

![chrome](https://cloud.githubusercontent.com/assets/3091060/12084478/96e271d2-b2bc-11e5-920f-3e721d42c440.png)

Gmail:

![gmail](https://cloud.githubusercontent.com/assets/3091060/12084481/9bee28e2-b2bc-11e5-9fb0-6edfbf995944.png)

**Comment by davehunt** [comment]
This could be a security feature of Gmail, not allowing inline CSS, JavaScript, or images from being displayed. It's not clear to me if you're sending an e-mail with the content of the report, or if the report is an attachment. Either way, I suspect the issue is with Gmail and not something I can fix in the plugin. If it turns out I'm wrong, please reopen this issue with details.

**Comment by tomer** [comment]
For the record, `--self-contained-html` should do the trick, but some content is blocked by Gmail, such as JavaScript code required for column-sorting and filtering, and they also cropping long HTML messages. Publishing the report as an email attachment also not perfect, as Gmail does filtering the HTML code for preview, so it is required to download the report from the email message and open it locally from the download folder.
